import { GoogleGenerativeAI } from '@google/generative-ai';
import { MODEL_CONFIG } from '../model-config';
import { Message } from '../store';

export class AgentSummary {
    private static readonly SUMMARY_PROMPT = `
You are the [Turn/Situation Summarizer] of a Text RPG.
Your job is to provide a rich, context-heavy summary of the "Current Situation".
The next AI turn (Router & Logic) will rely *solely* on this summary to understand what is happening, so it must contain ALL core information.

[Input]
Last Story Output: The very last narrative segment generated by the AI.

[Output Instructions]
- **Goal**: Provide a "High-Density Context" for the AI.
- **MUST Include**:
    - **Who**: All active characters present.
    - **What**: specific actions taken.
    - **Atmosphere/Status**: Current mood and physical states.
- **Constraint**: Do NOT use raw numbers like "HP: 10". Describe it as "severely injured" or "near death".
- **Structure**: Complete sentences. End with a period.
- **Length**: 2-3 sentences. Detailed enough to be a standalone context.
- **Language**: Korean (한국어).

[Example]
Input: (Story text about battle)
Output: 플레이어가 '철검'으로 고블린의 머리를 노렸으나 빗나갔고, 이에 격분한 고블린이 반격을 시도하고 있다. 좁은 동굴 안이라 피할 공간이 부족하여 매우 위급한 상황이다.

Input: (Story text about negotiation)
Output: 플레이어가 '희귀 약초'의 가치를 설명하며 상인을 설득하는 데 성공했다. 상인은 호기심 어린 눈빛으로 제안을 받아들이며 우호적인 태도로 가격 협상에 돌입했다.
`;

    static async summarize(
        apiKey: string,
        history: Message[], // Kept in signature for compatibility but unused
        lastStoryOutput: string
    ): Promise<{ summary: string; usageMetadata?: any; _debug_prompt?: string }> {
        // [Optimized] Use lightweight model
        const genAI = new GoogleGenerativeAI(apiKey);
        const model = genAI.getGenerativeModel({
            model: MODEL_CONFIG.SUMMARY || 'gemini-2.5-flash',
            generationConfig: {
                temperature: 0.3, // Factual
            }
        });

        // [Modified] User requested to remove Recent Context
        // focusing only on the Last Story Output for "Current Situation"

        const prompt = `
${this.SUMMARY_PROMPT}

[Last Story Output]
${lastStoryOutput}

[Current Situation Summary]:
`;

        try {
            const result = await model.generateContent(prompt);
            return {
                summary: result.response.text().trim(),
                usageMetadata: result.response.usageMetadata,
                _debug_prompt: prompt
            };
        } catch (error) {
            console.warn('[AgentSummary] Failed to generate summary:', error);
            return { summary: "", _debug_prompt: prompt, usageMetadata: undefined }; // Fail silently/gracefully
        }
    }
}
